import createClient from "openapi-fetch";
import type { paths } from "./v1"; // generated by openapi-typescript

const client = createClient<paths>({
  baseUrl: "http://localhost:400",
});

export default client;
