// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package model

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	Title     string             `json:"title"`
	Year      int32              `json:"year"`
	Runtime   int32              `json:"runtime"`
	Genres    []string           `json:"genres"`
	Version   int32              `json:"version"`
}
