openapi: 3.0.0
info:
  title: Movies API
  description: REST API for managing movies
  version: 1.0.0
servers:
  - url: http://localhost:400
    description: Local development server
paths:
  /v1/movies:
    post:
      summary: Create a new movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMovieRequest"
      responses:
        "201":
          description: Movie created successfully
          headers:
            Location:
              description: URL of the newly created movie
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  movie:
                    $ref: "#/components/schemas/Movie"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    get:
      summary: List all movies
      responses:
        "200":
          description: List of movies
          content:
            application/json:
              schema:
                type: object
                properties:
                  movies:
                    type: array
                    items:
                      $ref: "#/components/schemas/Movie"
  /v1/movies/{id}:
    get:
      summary: Get a movie by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Movie found
          content:
            application/json:
              schema:
                type: object
                properties:
                  movie:
                    $ref: "#/components/schemas/Movie"
        "404":
          description: Movie not found
    patch:
      summary: Update a movie
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateMovieRequest"
      responses:
        "200":
          description: Movie updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  movie:
                    $ref: "#/components/schemas/Movie"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "404":
          description: Movie not found
components:
  schemas:
    Movie:
      type: object
      required:
        - id
        - version
        - title
        - year
        - runtime
        - genres
      properties:
        id:
          type: integer
          format: int64
        version:
          type: integer
          format: int32
        title:
          type: string
          maxLength: 500
        year:
          type: integer
          format: int32
          minimum: 1888
          maximum: 2025
        runtime:
          type: string
          description: Runtime in minutes, formatted as "X min"
        genres:
          type: array
          minItems: 1
          maxItems: 5
          items:
            type: string
            uniqueItems: true
    CreateMovieRequest:
      type: object
      required:
        - title
        - year
        - runtimeMin
        - genres
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 500
        year:
          type: integer
          format: int32
          minimum: 1888
          maximum: 2025
        runtimeMin:
          type: integer
          format: int32
          minimum: 1
        genres:
          type: array
          minItems: 1
          maxItems: 5
          items:
            type: string
            uniqueItems: true
    UpdateMovieRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 500
        year:
          type: integer
          format: int32
          minimum: 1888
          maximum: 2025
        runtimeMin:
          type: integer
          format: int32
          minimum: 1
        genres:
          type: array
          minItems: 1
          maxItems: 5
          items:
            type: string
            uniqueItems: true
