// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"context"
)

type Querier interface {
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	GetMovie(ctx context.Context, id int64) (Movie, error)
	ListMovies(ctx context.Context) ([]Movie, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
}

var _ Querier = (*Queries)(nil)
